apiVersion: v1
kind: Service
metadata:
  name: solace-producer
  namespace: solace
  labels:
    app: solace-producer
spec:
  type: ClusterIP
  selector:
    app: solace-producer
  ports:
  - name: http
    port: 8080
    targetPort: 8080

