apiVersion: v1
kind: Service
metadata:
  namespace: solace
  name: solace-consumer
  labels:
    app: solace-consumer
spec:
  type: ClusterIP
  selector:
    app: solace-consumer
  ports:
  - name: http
    port: 8080
    targetPort: 8080

