FROM golang:1.23 AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY consumer.go .
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o consumer

FROM debian:12-slim
WORKDIR /app
COPY --from=builder /build/consumer ./consumer
COPY ./solclient-7.33.1.1 /usr/lib/solclient
ENV LD_LIBRARY_PATH=/usr/lib/solclient
ENTRYPOINT ["./consumer"]
